config/routes.rb
Rails.application.routes.draw do
	root to: 'teams#index'
  devise_for :users
  get '/drivers' => 'drivers#index'

  get '/drivers/show/:id' => 'drivers#show'

  get 'drivers/new'

  get 'drivers/create'

  get 'drivers/edit'

  get 'drivers/update'

  get '/drivers/delete/:id' => 'drivers#delete'

  get 'drivers/destroy'

  get '/teams' => 'teams#index'

  get '/teams/show/:id' => 'teams#show'

  get 'teams/new'

  get 'teams/create'

  get 'teams/edit'

  get 'teams/update'

  get '/teams/delete/:id' => 'teams#delete'

  get 'teams/destroy'
	resources :teams
	resources :drivers

	get 'signup'  => 'users#new'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
has_many :drivers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
before_action :authenticate_user!
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
	@drivers = Driver.all
  end

  def show
	@driver = Driver.find(params[:id])
  end

  def new
	@driver = Driver.new
  end

  def create
	@driver = Driver.new(driver_params)
	if @driver.save
	redirect_to(:action => 'index')
	else
	render('new')
	end
  end

  def edit
	@driver = Driver.find(params[:id])
  end

  def update
	@driver = Driver.finf(params[:id])
	if @driver.update_attributes(driver_params)
	redirect_to(:action => 'show', :id => driver.id)
	else
	render('index')
	end
  end

  def delete
	@driver = Driver.find(params[:id])
  end

  def destroy
	Driver.find(params[:id]).destroy
	redirect_to(:action => 'index')
  end

	private
	def driver_params
	params.require(:driver).permit(:name, :image, :bio, :shop)
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
	@teams = Team.all
  end

  def show
	@team = Team.find(params[:id])
	@drivers = @team.drivers
  end

  def new
	@team = Team.new
  end

  def create
	@team = Team.new(team_params)
	if @team.save
	redirect_to(:action => 'index')
	else
	render('new')
	end
  end

  def edit
	@team = Team.find(params[:id])
  end

  def update
	@team = Team.find(params[:id])
	if @team.update_attributes(team_params)
	redirect_to(:action => 'show', :id => @team.id)
	else
	render('index')
	end
  end

  def delete
	@team = Team.find(params[:id])
  end

  def destroy
	Team.find(params[:id]).destroy
	redirect_to(:action => 'index')
  end

	private
	def team_params
	params.require(:team).permit(:name, :image, :description, :shop)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :image %><br>
<%= f.url_field :image %><br>

<%= f.label :bio %><br>
<%= f.text_field :bio %><br>

<%= f.label :shop %><br>
<%= f.url_field :shop %><br>

<%= f.submit %>
<% end %>

app/views/drivers/create.html.erb
<h1>Drivers#create</h1>
<p>Find me in app/views/drivers/create.html.erb</p>

app/views/drivers/delete.html.erb
<h1>Delete driver</h1>
<p><strong>Name:</strong>
<%= @driver.name %></p>
<p><strong>Image:</strong>
<%= image_tag @driver.image %></p>
<p><strong>Bio:</strong>
<%= @driver.bio %></p>
<p><strong>Shop:</strong>
<%= @driver.shop %></p>

<%= link_to 'Delete', drivers_delete_path(:id => @driver.id) %>
<%= link_to 'Edit', edit_driver_path(@driver) %>
<%= link_to 'Back', drivers_path %>

app/views/drivers/destroy.html.erb
<h1>Drivers#destroy</h1>
<p>Find me in app/views/drivers/destroy.html.erb</p>

app/views/drivers/edit.html.erb
<h1>Edit driver</h1>
<%= render 'form' %>
<%= link_to "Back", drivers_path %>

app/views/drivers/index.html.erb
<div>
        <ul class="header-nav">
            <% if user_signed_in? %>
              Logged in as <strong>
                <%= current_user.email %>
              </strong>.
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => "btn btn-default" %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-default" %>
              <%= link_to "Sign in", new_user_session_path, :class => "btn btn-default" %>
            <% end %>
</ul>
</div>
<br>
<br>
<br>
<h1>Drivers</h1>
<% @drivers.in_groups_of(2).each do |driver| %>
<% drivers.select! {|x| !x.nil?} %>
<div class="row">
<% @drivers.each do |driver| %>
<div class="col-md-4">
<div class="caption">
<div class="listing-name"><%= driver.name %></div>
<div class="listing-image"><%= image_tag driver.image %></div>
<div class="listing-bio"><%= driver.bio %></div>
<div class="listing-shop"><%= driver.shop %></div>

<span><%= link_to "Show", driver %></span>
<span><%= link_to "Edit", edit_driver_path(driver.id) %></span>
<span><%= link_to "Destroy", driver, method: :delete, data: {confirm: "Are you sure?"} %></span>
<% end %>
<% end %>
</div>
</div>
</div>
<%= link_to "New driver", new_driver_path %>

app/views/drivers/new.html.erb
<h1>New driver</h1>
<%= render 'form' %>
<%= link_to "Back", drivers_path %>

app/views/drivers/show.html.erb
<div>
        <ul class="header-nav">
            <% if user_signed_in? %>
              Logged in as <strong>
                <%= current_user.email %>
              </strong>.
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => "btn btn-default" %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-default" %>
              <%= link_to "Sign in", new_user_session_path, :class => "btn btn-default" %>
            <% end %>
</ul>
</div>
<p>Driver name:</strong>
<p><%= @driver.name %></p>
<p>Driver image:</strong>
<p><%= image_tag @driver.image %></p>
<p>Driver bio:</strong>
<p><%= @driver.bio %></p>
<p>Driver shop:</strong>
<p><%= @driver.shop %></p>

<%= link_to "Edit", edit_driver_path(@driver) %>
<%= link_to "Back", drivers_path %>

app/views/drivers/update.html.erb
<h1>Drivers#update</h1>
<p>Find me in app/views/drivers/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.formula1.com/">official website of Formula 1</a>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://www.sportowefakty.pl/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Formula", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign up",   new_user_registration_path, :class => "btn btn-default"  %></li>
        <li><%= link_to "Sign in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formula</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="header">
      <div class="container">
        
       
      </div>
    </div>

    <%= yield %>

  </body>
</html>